osticket/api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('tk_create', views.tk_create, name='tk_create'),
    path('list_topic', views.list_topic, name='list_topic'),
]

osticket/osticket/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('user.urls', namespace='user')),
    path('agent/', include('agent.urls', namespace='agent')),
    path('api/', include('api.urls', namespace='api')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

osticket/user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

app_name = 'user'
urlpatterns = [
    path('logout/', views.logout_user, name='logout'),
    path('', views.login_user, name='login'),
    path('user/', views.homeuser, name='homeuser'),
    path('submitadmin/', views.submitadmin, name='submitadmin'),
    path('profile', views.detail_user, name='detail_user'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path(r'^resetpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.resetpwd, name='resetpassword'),
    path(r'^agresetpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.agresetpwd, name='agresetpassword'),
    path('user/history_<int:id>', views.history, name='history'),
    path('user/data/', views.user_data, name='user_data'),
]

osticket/user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token, account_activation_token1
from django.core.mail import EmailMessage
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.utils.safestring import mark_safe
from django.http import JsonResponse
from django.conf import settings
import json
from .forms import *
import string
import datetime
from random import *
from django.contrib.auth.decorators import login_required
min_char = 8
max_char = 12
allchar = string.ascii_letters + string.digits

MAX_UPLOAD_SIZE = 10485760
dic = {}
dic_time = {}


def history(request, id):
    if request.session.has_key('user') and (Users.objects.get(username=request.session['user'])).status == 1:
        tems = TicketLog.objects.filter(ticketid=id)
        result = []
        for tem in tems:
            if tem.userid is not None:
                action = "<b>User " + str(tem.userid.username) + "</b><br/>" + str(tem.action)
            else:
                action = "<b>Agent " + str(tem.agentid.username) + "</b><br/>" + str(tem.action)
            if tem.action == 'create ticket':
                cont = "<span class='glyphicon glyphicon-plus' ></span>"
            elif tem.action == 'close ticket':
                cont = "<span class='glyphicon glyphicon-off' ></span>"
            elif tem.action == 'assign ticket':
                cont = "<span class='glyphicon glyphicon-pushpin' ></span>"
            elif tem.action == 'done ticket':
                cont = "<span class='glyphicon glyphicon-ok' ></span>"
            elif tem.action == 're-process ticket':
                cont = "<span class='glyphicon glyphicon-refresh' ></span>"
            elif tem.action == 're-open ticket':
                cont = "<span class='glyphicon glyphicon-repeat' ></span>"
            elif tem.action == 'give up ticket':
                cont = "<span class='glyphicon glyphicon-log-out' ></span>"
            else:
                cont = "<span class='glyphicon glyphicon-user' ></span>"
            result.append({"id": tem.id,
                           "title": action,
                           "content": cont,
                           "group": "period",
                           "start": str(tem.date)+"T"+str(tem.time)[:-7]})
        maxtime = TicketLog.objects.filter(ticketid=id).latest('id')
        mintime = TicketLog.objects.filter(ticketid=id).earliest('id')
        if maxtime.ticketid.status == 0:
            status = '<font color="red">pending</font>'
        elif maxtime.ticketid.status == 1:
            status = '<font color="orange">processing</font>'
        elif maxtime.ticketid.status == 2:
            status = '<font color="green">done</font>'
        else:
            status = '<font color="gray">close</font>'
        tim = str(timezone.datetime.combine(maxtime.date, maxtime.time) - timezone.datetime.combine(
            mintime.date, mintime.time))[:-7]
        result.append({"id": 0,
                       "content": "Ticket no." + str(id) + " " + status + " (exist time " + tim + ")",
                       "type": "point",
                       "group": "overview",
                       "start": str(mintime.date) + "T" + str(mintime.time)[:-7]})
        tk = json.loads(json.dumps(result))
        return render(request, 'user/history.html', {'tk': tk, 'id': str(id)})
    else:
        return redirect("/")


def homeuser(request):
    if request.session.has_key('user') and (Users.objects.get(username=request.session['user'])).status == 1:
        user = Users.objects.get(username=request.session['user'])
        admin = Agents.objects.get(admin=1)
        form = CreateNewTicketForm()
        topic = Topics.objects.filter().order_by('-id')
        ticket = Tickets.objects.filter(sender=user.id).order_by('-id')
        handler = TicketAgent.objects.all()
        content = {'ticket': ticket,
                   'form': form,
                   'user': user,
                   'handler': handler,
                   'topic': topic,
                   'username': mark_safe(json.dumps(user.username)),
                   'fullname': mark_safe(json.dumps(user.fullname)),
                   'admin': mark_safe(json.dumps(admin.username)),
                   'noti_noti': user.noti_noti,
                    'noti_chat': user.noti_chat
                   }
        if request.method == 'POST':
            # user close ticket
            if 'tkid' in request.POST:
                ticket = Tickets.objects.get(id=request.POST['tkid'])
                ticket.status = 3
                ticket.save()
                
                TicketLog.objects.create(userid=user,
                                        ticketid=ticket,
                                        action='close ticket',
                                        date=timezone.now().date(),
                                        time=timezone.now().time())
                try:
                    tkag = TicketAgent.objects.filter(ticketid=request.POST['tkid']).values('agentid')
                except ObjectDoesNotExist:
                    pass
                else:
                    receiver = Agents.objects.filter(id__in=tkag)
                    for rc in receiver:
                        if rc.receive_email == 1:
                            email = EmailMessage('Closed ticket',
                                                 render_to_string('user/close_email.html',
                                                                  {'receiver': rc, 'sender': user, 'id': id}),
                                                 to=[rc.email],)
                            email.send()
            # user xem thông báo
            elif 'noti_noti' in request.POST:
                user.noti_noti = 0
                user.save()
            elif 'noti_chat' in request.POST:
                user.noti_chat = 0
                user.save()
            # user post info tạo ticket
            else:
                form = CreateNewTicketForm(request.POST,request.FILES)
                if form.is_valid():
                    topicA = Topics.objects.get(id=request.POST['topic'])
                    ticket = Tickets()
                    ticket.title = form.cleaned_data['title']
                    ticket.content = form.cleaned_data['content']
                    ticket.sender = user
                    ticket.topicid = topicA
                    ticket.datestart = timezone.now()
                    ticket.dateend = (timezone.now() + timezone.timedelta(days=3))
                    if request.FILES.get('attach') is not None:
                        if request.FILES['attach']._size < MAX_UPLOAD_SIZE:
                            ticket.attach = request.FILES['attach']
                            handle_uploaded_file(request.FILES['attach'])
                        else:
                            return render(request, 'user/home_user.html', content)
                    ticket.save()
                    TicketLog.objects.create(userid=user,
                                             ticketid=ticket,
                                             action='create ticket',
                                             date=timezone.now().date(),
                                             time=timezone.now().time())
                    # if topicA.type_send == 1:
                    #     for rc in receiver:
                    #         if rc.receive_email == 1:
                    #             email = EmailMessage('New ticket',
                    #                                 render_to_string('user/new_ticket.html', {}),
                    #                                 to=[rc.email],)
                    #             email.send()
                    # else:
                    #     email = EmailMessage('New ticket',
                    #                         render_to_string('user/new_ticket.html', {}),
                    #                         to=[admin.email],)
                    #     email.send()
                return redirect("/user")
            
        return render(request, 'user/home_user.html', content)
    else:
        return redirect("/")


# Hàm trả về table các ticket của user
def user_data(request):
    if request.session.has_key('user') and (Users.objects.get(username=request.session['user'])).status == 1:
        user = Users.objects.get(username=request.session['user'])
        tk = Tickets.objects.filter(sender=user.id).order_by('-id')
        data = []
        for tk in tk:
            if tk.status == 0:
                status = r'<span class ="label label-danger"> pending</span>'
                handler = '<p id="hd' + str(tk.id) + '">Nobody</p>'
            else:
                if tk.status == 1:
                    status = r'<span class ="label label-warning"> processing </span>'
                elif tk.status == 2:
                    status = r'<span class ="label label-success"> done </span>'
                else:
                    status = r'<span class ="label label-default"> closed </span>'
                handler = '<p id="hd' + str(tk.id) + '">'
                for t in TicketAgent.objects.filter(ticketid=tk.id):
                    handler += t.agentid.username + "<br>"
                handler += '</p>'
            id = '''<button type="button" class="btn" data-toggle="modal" data-target="#'''+str(tk.id)+'''content">'''+str(tk.id)+'''</button>'''
            option = ''
            if tk.status < 3:

osticket/user/templates/user/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

osticket/user/templates/user/agresetpwd.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to reset your password,
http://{{ domain }}{% url 'user:agresetpassword' uidb64=uid token=token %}
{% endautoescape %}

osticket/user/templates/user/close_email.html
{% autoescape off %}
Hi {{ receiver.fullname }},
{{sender.fullname}} was closed ticket no.{{id}}
{% endautoescape %}

osticket/user/templates/user/confirm_admin.html
{% autoescape off %}
Hi {{ agent.username }},
Mã xác thực đăng nhập của bạn là: {{ code }}
{% endautoescape %}

osticket/user/templates/user/conversation.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="{% static 'css/chat.css' %}" type="text/css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>  
    <title>Chat Room</title>
</head>
<body>
    <h2>Chat Messages</h2>

    <div class="col-sm-3 col-sm-offset-4 frame">
        <ul></ul>
        <div>
            <div class="msj-rta macro">                        
                <div class="text text-r" style="background:whitesmoke !important">
                    <input id="chat-message-input" class="mytext" placeholder="Type a message"/>
                </div>
            </div>
            <div style="padding:10px;">
                <span id="chat-message-submit" class="glyphicon glyphicon-share-alt"></span>
            </div>                
        </div>
    </div>
    <input id="who" type="hidden" value="{{ who }}"/>

</body>
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/' + roomName + '/');

    var me = {};
    me.avatar = "https://scontent.fhan3-2.fna.fbcdn.net/v/t1.0-9/22885865_1722296451175676_8315630450281336486_n.jpg?_nc_cat=0&_nc_eui2=v1%3AAeF3N32BRG1HfiI6wYFOD0syQnWULRna1ynbA4X_9isP5U9OTYpX393weyHM7i53ld34rFsOa0PdREWLJij8FWXIF0EfX1p8u3GUsxq_xcyEsw&oh=733c482517a19a82689b73cea0f35a4e&oe=5B58D2E3";

    var you = {};
    you.avatar = "https://scontent.fhan3-2.fna.fbcdn.net/v/t1.0-9/14732373_1224510360954290_7402332525860387467_n.jpg?_nc_cat=0&_nc_eui2=v1%3AAeHKXwDy_s1iK9FoOwayfi1qoOsIZlCm_H_ILhjIlp7LpK_1UzL2lTNdV6hbvFqTDhhJngiHagzjXZdsq1veAd6UGPEJKNXC4eyjPt-BNHGNUA&oh=6e9c0ee4c9352e7446fdef79a9037cd7&oe=5B5799DF";

    function formatAMPM(date) {
        var hours = date.getHours();
        var minutes = date.getMinutes();
        var ampm = hours >= 12 ? 'PM' : 'AM';
        hours = hours % 12;
        hours = hours ? hours : 12; // the hour '0' should be '12'
        minutes = minutes < 10 ? '0'+minutes : minutes;
        var strTime = hours + ':' + minutes + ' ' + ampm;
        return strTime;
    }            

    //-- No use time. It is a javaScript effect.
    function insertChat(who, text, time){
        if (time === undefined){
            time = 0;
        }
        var control = "";
        var date = formatAMPM(new Date());
        
        if (who == "me"){
            control = '<li style="width:100%">' +
                            '<div class="msj macro">' +
                            '<div class="avatar"><img class="img-circle" style="width:100%;" src="'+ me.avatar +'" /></div>' +
                                '<div class="text text-l">' +
                                    '<p>'+ text +'</p>' +
                                    '<p><small>'+date+'</small></p>' +
                                '</div>' +
                            '</div>' +
                        '</li>';                    
        }else{
            control = '<li style="width:100%;">' +
                            '<div class="msj-rta macro">' +
                                '<div class="text text-r">' +
                                    '<p>'+text+'</p>' +
                                    '<p><small>'+date+'</small></p>' +
                                '</div>' +
                            '<div class="avatar" style="padding:0px 0px 0px 10px !important"><img class="img-circle" style="width:100%;" src="'+you.avatar+'" /></div>' +                                
                    '</li>';
        }
        setTimeout(
            function(){                        
                $("ul").append(control).scrollTop($("ul").prop('scrollHeight'));
            }, time);
        
    }

    function resetChat(){
        $("ul").empty();
    }

    /*$(".mytext").on("keydown", function(e){
        if (e.which == 13){
            var text = $(this).val();
            if (text !== ""){
                insertChat("me", text);              
                $(this).val('');
            }
        }
    });*/

    $('body > div > div > div:nth-child(2) > span').click(function(){
        $(".mytext").trigger({type: 'keydown', which: 13, keyCode: 13});
    })

    //-- Clear Chat
    //resetChat();

    //-- Print Messages

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        var who = data['who'];
        //document.querySelector('#chat-log').value += (message + '\n');
        insertChat(who, message, 0);
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };



    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };
    

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        var hi = document.querySelector('#who');
        var who = hi.value;

        if (message != ""){
            chatSocket.send(JSON.stringify({
                'message' : message,
                'who' : who
            }));
    
        }
        messageInputDom.value = '';
    };

</script>
</html>

osticket/user/templates/user/detail_user.html
{% extends 'user/base.html' %}
    {% load staticfiles %}
{% block title %}Profile{% endblock %}
    {% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Your profile
      </h1>
      <ol class="breadcrumb">
        <li><a ><i class="fa fa-home"></i> Home</a></li>
        <li class="active">Profile</li>
      </ol>
    </section>

  <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-striped table-bordered" id="info-user">
                  <tbody>
                    <tr>
                        <td>Fullname</td>
                      <td id="full_name">{{ user.fullname }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                      <td id="email_user">{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td>Username</td>
                      <td>{{ user.username }}</td>
                    </tr>
                    <tr>
                        <td>Phone</td>
                      <td id="phone_user">{{user.phone}}</td>
                    </tr>
                    <tr>
                        <td>Receive email</td>
                      {% if user.receive_email == 1 %}
                            <td id="rc_email">Yes</td>
                        {% else %}
                            <td id="rc_email">No</td>
                      {% endif%}
                    </tr>
                    <tr>
                        <td>Status</td>
                      {% if user.status == 0 %}
                        <td><span class="label label-danger">inactive</span></td>
                        {% else %}
                        <td><span class="label label-success">active</span></td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Date created</td>
                      <td>{{ user.created }}</td>
                    </tr>
                  </tbody>
                </table>
                <button type="button" class="btn btn-primary info_agent" id="{{ user.id }}" data-toggle="modal" data-title="change" data-target="#topicModal" >
                        <span class="glyphicon glyphicon-wrench"> Change info</span>
                </button>

                <button type="button" class="btn btn-primary pwd_agent" id="{{ user.id }}" data-toggle="modal" data-title="change_pwd" data-target="#topicModal" >
                        <span class="glyphicon glyphicon-wrench" id="{{user.password}}" name='pwd_current'> Change password</span>
                </button>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% csrf_token %}
<div id="topicModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="title"></h3>
            </div>
            <div class="modal-body form-group">
                <div id="info">
                    <label for="fullname"><b>Full name</b></label>
                    <input class="inputText form-control" type="text" placeholder="Full name" name="fullname" >

                    <label for="email"><b>Email</b></label>
                    <input class="inputText form-control" type="text" placeholder="Enter Email" name="email">

                    <label for="phone"><b>Phone</b></label>
                    <input class="inputText form-control" type="text" placeholder="Enter your phone number" name="phone">
                    <br/>
                    <input class="inputText" style="transform: scale(2)" type="checkbox" name="receive_mail" > <b>   Receive Email?</b>
                </div>

                <div id="pwd">
                    <label for="psw-current"><b>Current Password</b></label>
                    <input class="inputText form-control" type="password" placeholder="Enter current Password" name="current_password">

                    <label for="psw"><b>Password</b></label>
                    <input class="inputText form-control" type="password" placeholder="Enter new Password" name="password">

                    <label for="psw-repeat"><b>Repeat Password</b></label>
                    <input class="inputText form-control" type="password" placeholder="Repeat new Password" name="password2">
                </div>

                <input type="hidden" name="userid" value="">

            </div>
            <div class="modal-footer">
                <button type="button" id="changeuser" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal" id = "change_user_close">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/detail_user.js' %}"></script>
{% endblock %}

osticket/user/templates/user/formresetpass.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Reset Password</title>
</head>
<body>
    <br/>
    <br/>
    <div class="container" id="id04">
        <div class="panel panel-info">
            <div class="panel-heading">
                Reset password
            </div>
            <div class="panel-body">
                <form action="" method="POST" onsubmit="return validate()">
                    {% csrf_token %}
                    <label for="pwd1"><b>New password</b></label>
                    <input type="password" class="form-control" id="pwd1" name="pwd1" required>
                    <div class="invalid-msg" id="invalid-msg1"></div><br>

                    <label for="pwd2"><b>Retype </b></label>
                    <input type="password" class="form-control"id="pwd2" name="pwd2" required>
                    <div class="invalid-msg" id="invalid-msg2"></div><br/>
                    <button type="submit" class="btn btn-primary" value="OK" id="uemail" >Change</button>
                </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
    function validate(){
        $('#invalid-msg1').html('');
        $('#invalid-msg2').html('');
        if($('#pwd1').val() != $('#pwd2').val() ){
            $('#invalid-msg2').html('<em>re-password is in correct</em>').css('color','red');
            return false;
        }
        return true;
    }
</script>
</body>
</html>

osticket/user/templates/user/history.html
{% extends 'user/base.html' %}
    {% load staticfiles %}
{% block title %}History{% endblock %}
{% block lib %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="{% static 'history/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content-header">
      <h3>Timeline of ticket no.{{ id }}</h3>
      <ol class="breadcrumb">
        <li><a ><i class="fa fa-home"></i> Home</a></li>
        <li class="active">Tickets</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <!-- /.box-header -->
            <div class="box-body">
                <div id="visualization"></div>
                <br/>
                <div>
                    <button style="float:left;" class="btn btn-primary" onclick="reset()">Reset</button>
                    <h3 style="float:right;">scroll mouse to zoom +/-</h3>
                </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}
{% block js%}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.js"></script>
<script type="text/javascript">
    var groups = new vis.DataSet([
        {
            id: 'overview',
            content:'overview'
        },
        {
            id: 'period',
            content:'period'
        }
    ]);
    var tem = JSON.stringify({{tk|safe}});
    var data = JSON.parse(tem);
    var items = new vis.DataSet();
    items.add(data);
    var container = document.getElementById('visualization');
    var options = {
      height: '400px',
      min: new Date(2018, 0, 1),                // lower limit of visible range
      max: new Date(2019, 0, 1),                // upper limit of visible range
      zoomMin: 1000 * 60 * 10 ,                     // a min in milliseconds
      zoomMax: 1000 * 60 * 60 * 24 * 31 ,     // about a months in milliseconds
    };
    var timeline = new vis.Timeline(container, items, groups, options);
    timeline.fit();
    function reset(){
        timeline.fit();
    }
</script>
{% endblock %}

osticket/user/templates/user/new_ticket.html
{% autoescape off %}
Hi all,
A ticket was sent to our system!
Please login to process!
Thanks!
{% endautoescape %}

osticket/user/templates/user/resetpwd.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to reset your password,
http://{{ domain }}{% url 'user:resetpassword' uidb64=uid token=token %}
{% endautoescape %}

osticket/user/templates/user/submit_code_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Submit code</title>
</head>
<body>
    <br/>
    <br/>
    <div class="container" id="id05">
        <div class="panel panel-info">
            <div class="panel-heading">{{ mess }}</div>
            <div class="panel-body">
                <form method="POST">
                {% csrf_token %}
                <div class="modal-body form-group">
                    <input class="form-control" type="text" placeholder="Enter your code" name="code">
                    <div class="invalid-msg"></div><br/>
                    <button class="btn btn-primary" type="submit" value="OK" id="uemail" style="width:100%;" >OK</button><br/><br/>
                </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>