osticket/agent/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'agent'
urlpatterns = [
    path('admin/', views.home_admin, name='home_admin'),
    path('admin/data', views.home_admin_data, name='home_admin_data'),
    path('topic/', views.manager_topic, name='manager_topic'),
    path('department/', views.manager_department, name='manager_department'),
    path('agent/', views.manager_agent, name='manager_agent'),
    path('', views.home_agent, name="index"),
    path('logout', views.logout, name="logout"),
    path('assign/<int:id>', views.assign_ticket, name="assign_ticket"),
    path('history/<int:id>', views.history, name="history"),
    path('history_all_ticket/<str:date>_<str:date2>', views.history_all_ticket, name="history_all_ticket"),
    path('inbox', views.inbox, name="inbox"),
    path('outbox', views.outbox, name="outbox"),
    path('processing_ticket/', views.processing_ticket, name="processing_ticket"),
    path('processing_ticket/data', views.processing_ticket_data, name="processing_ticket_data"),
    path('closed_ticket', views.closed_ticket, name='closed_ticket'),
    path('manage_user/', views.manager_user, name="manage_user"),
    path('manage_user/data', views.manage_user_data, name="manage_user_data"),
    path('profile', views.profile, name="profile"),
    path('logout_admin/', views.logout_admin, name='logout_admin'),
]

osticket/api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('tk_create', views.tk_create, name='tk_create'),
    path('list_topic', views.list_topic, name='list_topic'),
]

osticket/osticket/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('user.urls', namespace='user')),
    path('agent/', include('agent.urls', namespace='agent')),
    path('api/', include('api.urls', namespace='api')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

osticket/agent/models.py
from django.db import models

# Create your models here.

osticket/agent/forms.py
from django import forms
from user.models import *


class ForwardForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Text here',
            'width': 'auto',
            'height': 'auto',
        }
    ))
    # receiver = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
    #                           choices=[(x.id, x.fullname) for x in Agents.objects.all()])


class AddForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Text here',
            'width': 'auto',
            'height': 'auto',
        }
    ))
    # receiver = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
    #                           choices=[(x.id, x.fullname) for x in Agents.objects.all()])

osticket/agent/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils import timezone

from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse

from user.models import *
from .forms import ForwardForm, AddForm
from django.core.mail import EmailMessage
import simplejson as json
from django.utils.safestring import mark_safe
import json
import string
import os
from datetime import datetime
from datetime import timedelta
min_char = 8
max_char = 12
allchar = string.ascii_letters + string.digits


# Create your views here.
def home_admin(request):
    if request.session.has_key('admin'):
        admin = Agents.objects.get(username=request.session['admin'])
        agent = Agents.objects.exclude(username=request.session['admin'])
        agent_total = Agents.objects.count()
        tk_processing = Tickets.objects.filter(Q(status=1) | Q(status=2)).count()
        tk_done = Tickets.objects.filter(status=3).count()
        tk_open = Tickets.objects.filter(status=0).count()
        # tpag = TopicAgent.objects.filter(agentid=sender).values('topicid')
        tp = Topics.objects.all()
        list_ag = {}
        for t in tp:
            ag = TopicAgent.objects.filter(topicid=t, agentid__in=agent)
            list_ag[t.name] = [a.agentid for a in ag]
        content = {'ticket': Tickets.objects.filter().order_by("-id"),
                   'list_ag': list_ag,
                   'topic': tp,
                   'handler': TicketAgent.objects.all(),
                   'admin': admin,
                   'today': timezone.now().date(),
                   'agent': agent,
                   'agent_name': mark_safe(json.dumps(admin.username)),
                   'fullname': mark_safe(json.dumps(admin.fullname)),
                   'agent_total': agent_total,
                   'tk_open': tk_open,
                   'tk_processing': tk_processing,
                   'tk_done': tk_done}
        if request.method == 'POST':
            if 'close' in request.POST:
                ticketid = request.POST['close']
                tk = Tickets.objects.get(id=ticketid)
                if tk.status == 3:
                    if not TicketAgent.objects.filter(ticketid=tk):
                        tk.status = 0
                        action = "re-open ticket"
                    else:
                        tk.status = 1
                        action = "re-process ticket"
                else:
                    tk.status = 3
                    action = "close ticket"
                tk.save()
                TicketLog.objects.create(agentid=admin, ticketid=tk,
                                         action=action,
                                         date=timezone.now().date(),
                                         time=timezone.now().time())
            elif 'delete' in request.POST:
                ticketid = request.POST['delete']
                tk = Tickets.objects.get(id=ticketid)
                tk.delete()
                try:
                    os.remove(r'notification/chat/chat_'+ticketid+'.txt')
                except:
                    pass
            elif 'ticketid' in request.POST:
                list_agent = request.POST['list_agent[]']
                list_agent = json.loads(list_agent)
                ticketid = request.POST['ticketid']
                if not list_agent:
                    try:
                        tk = Tickets.objects.get(id=ticketid)
                        tkag1 = TicketAgent.objects.filter(ticketid=tk)
                        tkag1.delete()
                        tk.status = 0
                        tk.save()
                        action = "received ticket forward from (admin)" + admin.username
                        tklog = TicketLog.objects.filter(action=action)
                        tklog.delete()
                    except:
                        tk.status = 0
                        tk.save()
                else:
                    try:
                        tk = Tickets.objects.get(id=ticketid)
                        tkag1 = TicketAgent.objects.filter(ticketid=tk)
                        tkag1.delete()
                        action = "received ticket forward from (admin)" + admin.username
                        tklog = TicketLog.objects.filter(action=action)
                        tklog.delete()
                    except:
                        pass
                    for agentid in list_agent:
                        agent = Agents.objects.get(username=agentid)
                        tk = Tickets.objects.get(id=ticketid)
                        tkag = TicketAgent(agentid=agent, ticketid=tk)
                        tkag.save()
                        tk.status = 1
                        tk.save()
                        action = "received ticket forward from (admin)" + admin.username
                        if agent.receive_email == 1:
                            email = EmailMessage(
                                'Forward ticket',
                                render_to_string('agent/mail/forward_mail_leader.html',
                                                 {'receiver': agent,
                                                #   'domain': (get_current_site(request)).domain,
                                                  'domain': "113.190.232.90:8892",
                                                  'sender': 'Leader'}),
                                to=[agent.email],
                            )
                            email.send()
                        TicketLog.objects.create(agentid=agent, ticketid=tk,
                                                 action=action,
                                                 date=timezone.now().date(),
                                                 time=timezone.now().time())
        return render(request, 'agent/home_admin.html', content)
    else:
        return redirect('/')


def home_admin_data(request):
    if request.session.has_key('admin'):
        tk = Tickets.objects.filter().order_by("-id")
        data = []
        for tk in tk:
            if tk.status == 0:
                status = r'<span class ="label label-danger" id="leader'+str(tk.id)+'">pending</span>'
                handler = '<p id="hd' + str(tk.id) + '">Nobody</p>'
            else:
                if tk.status == 1:
                    status = r'<span class ="label label-warning" id="leader'+str(tk.id)+'">processing</span>'
                elif tk.status == 2:
                    status = r'<span class ="label label-success" id="leader'+str(tk.id)+'">done</span>'
                else:
                    status = r'<span class ="label label-default" id="leader'+str(tk.id)+'">closed</span>'
                handler = '<p id="hd' + str(tk.id) + '">'
                for t in TicketAgent.objects.filter(ticketid=tk.id):
                    handler += t.agentid.username + "<br>"
                handler += '</p>'
            id = r'''<button type="button" class="btn" data-toggle="modal" data-target="#'''+str(tk.id)+'''content">'''+str(tk.id)+'''</button>'''
            sender = '<p id="sender' + str(tk.id) + '">' + tk.sender.username + '</p>'
            topic = '<p id="tp' + str(tk.id) + '">' + tk.topicid.name + '</p>'
            option = r'''<button type="button" class="btn btn-primary" id="'''+str(tk.id)+'''" data-toggle="tooltip" title="open/close"><i class="fa fa-power-off"></i></button>
            <button type="button" class="btn btn-danger" id="'''+str(tk.id)+'''" data-toggle="tooltip" title="delete"><i class="fa fa-trash-o"></i></button>
            <button type="button" class="btn btn-info" data-title="forward" id="'''+str(tk.id)+'''"data-toggle="modal" data-target="#forward_modal"><i class="fa fa-share-square-o" data-toggle="tooltip" title="forward" ></i></button>
            <a type="button" target=_blank class="btn btn-warning" href="/agent/history/'''+str(tk.id)+ '''" data-toggle="tooltip" title="history"><i class="fa fa-history"></i></a>'''
            data.append([id, tk.title, topic, sender, status, handler, option])
        ticket = {"data": data}
        tickets = json.loads(json.dumps(ticket))
        return JsonResponse(tickets, safe=False)


def manager_topic(request):
    if request.session.has_key('admin'):
        admin = Agents.objects.get(username=request.session['admin'])
        agent = Agents.objects.exclude(username=request.session['admin'])
        department = Departments.objects.exclude(name='admin').order_by('-id')
        list_ag = {}
        dm = Departments.objects.all()
        for dm in dm:
            list_ag[dm.name] = get_list_agent(dm.name)
        list_ag_tp = {}
        tp = Topics.objects.all()
        for tp in tp:
            list_ag_tp[tp.name] = get_agent_tp(tp.name)
        content = {'topic': Topics.objects.all(), 'admin': admin, 'today': timezone.now().date(), 'agent_name': mark_safe(json.dumps(admin.username)),
                   'fullname': mark_safe(json.dumps(admin.fullname)), 'agent':agent, 'department': department, 'list_ag': list_ag.items(), 'list_ag_tp': list_ag_tp.items(),}
        if request.method == 'POST':
            if 'close' in request.POST:
                topictid = request.POST['close']
                tp = Topics.objects.get(id=topictid)
                if tp.status == 0:
                    tp.status = 1
                else:
                    tp.status = 0
                tp.save()
            elif 'delete' in request.POST:
                topictid = request.POST['delete']
                tp = Topics.objects.get(id=topictid)
                tk = Tickets.objects.filter(topicid=tp)

osticket/agent/templates/agent/base_leader.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/lib/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
        {% block lib %}{% endblock %}
    <link href="{% static 'css/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:** -->
    <!--[if lt IE 9]>
    <script src="https:**oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https:**oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

<![endif]-->
</head>

<body class="fix-header fix-sidebar">
    <!-- Preloader - style you can find in spinners.css -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
			<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- Main wrapper  -->
    <div id="main-wrapper">
        <!-- header header  -->
        <div class="header">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <!-- Logo -->
                <div class="navbar-header" >
                    <a class="navbar-brand" href="{% url 'agent:home_admin' %}">
                        <span><img src="{% static 'images/meditech.png' %}" alt="homepage" style="width:260px;height:40px;"></span>
                    </a>
                </div>
                <!-- End Logo -->
                <div class="navbar-collapse">
                    <!-- toggle and nav items -->
                    <ul class="navbar-nav mr-auto mt-md-0">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted  " href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                        <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                        <!-- Messages -->
                        <!-- End Messages -->
                    </ul>
                    <!-- User profile and search -->
                    <ul class="navbar-nav my-lg-0">
                        <!-- Profile -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted  " href="{% url 'agent:logout_admin' %}"><i class="fa fa-power-off"></i> Logout</a>
                            <div class="dropdown-menu dropdown-menu-right animated zoomIn">
                                <ul class="dropdown-user">
                                    <li><a href="{% url 'agent:logout_admin' %}"><i class="fa fa-power-off"></i> Logout</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- End header header -->
        <!-- Left Sidebar  -->
        <div class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                    	<li class="nav-label">Master Admin</li>
                        <li><a href="{% url 'agent:home_admin' %}"><i class="fa fa-ticket"></i> Tickets </a></li>
                        <li><a href="{% url 'agent:manager_department' %}"><i class="fa fa-group"></i> Departments </a></li>
                        <li><a href="{% url 'agent:manager_agent' %}"><i class="fa fa fa-user-secret"></i> Agents </a></li>
                        <li><a href="{% url 'agent:manager_topic' %}"><i class="fa fa-list-alt"></i> Topics </a></li>
                        <li><a href="{% url 'agent:history_all_ticket' today|safe today|safe %}"><i class="fa fa-history"></i> History all ticket </a></li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </div>
        <!-- End Left Sidebar  -->
        <!-- Page wrapper  -->
        {% block content %}{% endblock %}
        
    </div>
    <!-- End Wrapper -->
    <!-- All Jquery -->
    <script src="{% static 'js/lib/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'js/lib/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'js/lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'js/lib/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/lib/datatables/datatables.min.js' %}"></script>
<script>
    var fullname = {{ fullname }};
    var agentName = {{ agent_name }};
    /*var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/agent/' + agentName + '/');*/

    var group_agent_Socket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/agent/'+agentName+'+group_agent_Socket/');

    


    function formatAMPM(date) {
        var hours = date.getHours();
        var minutes = date.getMinutes();
        var ampm = hours >= 12 ? 'PM' : 'AM';
        hours = hours % 12;
        hours = hours ? hours : 12; // the hour '0' should be '12'
        minutes = minutes < 10 ? '0'+minutes : minutes;
        var strTime = hours + ':' + minutes + ' ' + ampm + ' ' +date.getDate()+'/'+date.getMonth()+'/'+date.getFullYear();
        return strTime;
    }

    $(".point").hide();

    $(".fa-bell").click(function(){
        $(".point").hide();
    });


    group_agent_Socket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        // Thong bao va load lai table home_agent khi co new ticket hoac co 1 agent nhan xu ly ticket
        setTimeout(function(){
            $('#list_ticket_leader').DataTable().ajax.reload();
            $("body #pending").load(location.href + " #pending");
            $("body #processing").load(location.href + " #processing");
            $("body #done").load(location.href + " #done");
        }, 1000);
    };
</script>
{% block js %}{% endblock %}
</body>
</html>

osticket/agent/templates/agent/history_all_ticket.html
{% extends 'agent/base_leader.html' %}
{% block title %} History {% endblock %}
{% load staticfiles %}
{% block content %}
    <div class="page-wrapper">
            <!-- Bread crumb -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-primary">History</h3> </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active">History</li>
                    </ol>
                </div>
            </div>
            <!-- Container fluid  -->
                {% csrf_token %}
            <div class="container-fluid">
                <!-- Start Page Content -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-title">
                                <button class="btn btn-primary" data-toggle="modal" data-target="#filter">
                                    <i class="fa fa-search"></i> Filter
                                </button>
                                <div style="float:right;"><h2>View from {{day1|safe}} to {{day2|safe}}</h2></div>
                            </div>
                            <div class="card-body">
                                <table id="tb" class="display nowrap table table-hover table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th width="12%">Time</th>
                                            <th width="18%">Date</th>
                                            <th width="5%">Ticket</th>
                                            <th width="20%">Person</th>
                                            <th width="45%" style="text-align: left;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for v in tickets %}
                                        <tr>
                                            <td>{{v.time}}</td>
                                            <td>{{v.date}}</td>
                                            <td><a target="_blank" href="{% url 'agent:home_admin' %}">#{{v.ticketid.id}}</a></td>
                                            {% if v.userid is not None %}
                                            <td >(user) {{v.userid.username}}</td>
                                            {% else %}
                                            <td>(agent) <a target="_blank" href="{% url 'agent:manager_agent' %}">{{v.agentid.username}}</a></td>
                                            {% endif %}
                                            <td style="text-align: left;"><a target="_blank" href="{% url 'agent:history' v.ticketid.id %}"> {{v.action}}</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End PAge Content -->
            </div>
            <!-- End Container fluid  -->
            <!-- footer -->
            <!-- End footer -->
        </div>
    </div>
<div id="filter" class="modal" role="dialog">
  <div class="modal-dialog modal-sm">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Filter</h4>
      </div>
      <div class="modal-body">
          <label for="content">View from</label><br/>
             <input id="date" class="form-control" type="date" value="{{day1|safe}}" ><br/>
          <div id="invalid-date"><font color="red"></font></div>
         <label for="content2">to</label>
             <input id="date2" class="form-control" type="date" value="{{day2|safe}}" ><br/>
          <div id="invalid-date2"><font color="red"></font></div>
            <br/>
      </div>
      <div class="modal-footer">
         <button type="submit" class="btn btn-primary" id="update">Update</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/lib/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/lib/datatables/datatables-init.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('.dtt').DataTable();
            function isValidDate(dateString) {
                var regEx = /^\d{4}-\d{2}-\d{2}$/;
                if(!dateString.match(regEx)) return false;
                var d = new Date(dateString);
                if(!d.getTime() && d.getTime() !== 0) return false;
                return d.toISOString().slice(0,10) === dateString;
            }
            $('#update').click(function(){
                var date = $("#date").val();
                var date2 = $("#date2").val();
                if (!isValidDate(date)){
                    $("#invalid-date").html("invalid date");
                }
                else if(!isValidDate(date2)){
                    $("#invalid-date2").html("invalid date");
                }
                else{
                    location.href="/agent/history_all_ticket/"+$('#date').val()+"_"+$('#date2').val();
                }
            });
        });
    </script>
<script>
    $('#tb').dataTable( {
        paging: false,
        dom: 'Bfrtip',
        buttons: ['excel', 'pdf', 'print'],
        "order": [[ 1, "desc" ],[ 0, "desc" ],],
    } );
</script>
{% endblock %}

osticket/agent/templates/agent/manage_user.html
{% extends 'agent/base.html' %}
{% load static %}
{% block title %}Agent{% endblock %}
{% block js %}  
{% endblock%}
{% block content %}
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Manage user</h3> </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                <li class="breadcrumb-item active">Manage user</li>
            </ol>
        </div>
    </div>
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            
            <!-- /# column -->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Manage user</h4>
                    </div>
                    
                    <div class="card-body">
                        <table id="list_user" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Fullname</th>
                                    <th>Email</th>
                                    <th>Username</th>
                                    <th>Status</th>
                                    <th>Created</th>
                                    <th>Option</th>
                                </tr>
                            </thead>

                            
                            <!--<tbody>-->
                                <!--{% for tk in user %}-->
                                <!--<tr>-->
                                    <!--<th scope="row">{{tk.id}}</th>-->
                                    <!--<td>{{tk.fullname}}</td>-->
                                    <!--<td>{{tk.email}}</td>-->
                                    <!--<td>{{tk.username}}</td>-->
                                    <!--{% if tk.status == 0 %}-->
                                    <!--<td id="stt{{tk.id}}"><span class="label label-danger">inactive</span></td>-->
                                    <!--<td>{{tk.created}}</td>-->
                                    <!--<td id="button{{tk.id}}">-->
                                        <!--<button id="{{tk.id}}" class="unblock btn btn-success" type="button" data-toggle="tooltip" title="unblock" >-->
                                            <!--<span class="glyphicon glyphicon glyphicon-ok" ></span> Unblock-->
                                        <!--</button>-->
                                    <!--</td>-->
                                    <!--{% else %}-->
                                    <!--<td id="stt{{tk.id}}"><span class="label label-success">active</span></td>-->
                                    <!--<td>{{tk.created}}</td>-->
                                    <!--<td id="button{{tk.id}}">-->
                                        <!--<button id="{{tk.id}}" class="block btn btn-danger" type="button" data-toggle="tooltip" title="block" >-->
                                            <!--<span class="glyphicon glyphicon-lock" ></span> Block-->
                                        <!--</button>-->
                                    <!--</td>-->
                                    <!--{% endif %}-->
                                <!--</tr>-->
                                <!--{%endfor%}-->
                            <!--</tbody>-->
                            
                        </table>
                    </div>
                </div>
            </div>
       </div>     
    </div>
<!-- End Container fluid  -->
<!-- footer -->
<!-- End footer -->
</div>

<script src="{% static 'js/lib/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/lib/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'js/lib/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'js/sidebarmenu.js' %}"></script>
<script src="{% static 'js/lib/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/lib/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/manage_user.js' %}"></script>

{% endblock%}